# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
s="Hi there  sam"
s=s.split()
print(s);

['Hi', 'there', 'sam']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
planet="Earth"
diameter=12742
print('diameter of {} is {} kilometer.' .format (planet,diameter));

diameter of Earth is 12742 kilometer.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
d={'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [ ]:
np.arange(20,36)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
print(c)

[5 7 9]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [ ]:
import pandas as pd 
data={'name':['tom','nick','juli'],'age':[10,15,20]}
df=pd.DataFrame(data)
df

name  age
0   tom   10
1  nick   15
2  juli   20

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
import pandas as  pd
per1=pd.date_range(start='1-1-2023',end='1-2-2023',freq='2H')
for val in per1:
    print(val)

2023-01-01 00:00:00
2023-01-01 02:00:00
2023-01-01 04:00:00
2023-01-01 06:00:00
2023-01-01 08:00:00
2023-01-01 10:00:00
2023-01-01 12:00:00
2023-01-01 14:00:00
2023-01-01 16:00:00
2023-01-01 18:00:00
2023-01-01 20:00:00
2023-01-01 22:00:00
2023-01-02 00:00:00


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
import pandas as pd 
lst=[['1','aaa',22],['2','bbb',25],[3,'ccc',24]]
df=pd.DataFrame(lst,columns=['no','name','age'],dtype=float)
print(df)

    no name   age
0  1.0  aaa  22.0
1  2.0  bbb  25.0
2  3.0  ccc  24.0


C:\Users\91892\AppData\Local\Temp\ipykernel_2000\1057730756.py:3: FutureWarning: Could not cast to float64, falling back to object. This behavior is deprecated. In a future version, when a dtype is passed to 'DataFrame', either all columns will be cast to that dtype, or a TypeError will be raised.
  df=pd.DataFrame(lst,columns=['no','name','age'],dtype=float)
